# Temporary workflow to build Linux and macOS binaries directly with Meson

name: Direct

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    container: ghcr.io/openslide/linux-builder:latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: direct-cache
          path: subprojects/packagecache
      - name: Build
        run: |
          meson setup build --native-file machines/native-linux-x86_64.ini \
              -Dopenslide_werror=true
          meson compile -C build
          DESTDIR=install meson install -C build
          mkdir output
          cp build/install/{bin/slidetool,lib64/libopenslide.so.1} output/
          cd output
          for f in libopenslide.so.1 slidetool; do
              objcopy --only-keep-debug $f ${f}.debug
              objcopy -S --add-gnu-debuglink=${f}.debug $f ${f}.new
              mv ${f}.new $f
          done
          patchelf --set-rpath '$ORIGIN' slidetool
      - name: Smoke test
        run: OPENSLIDE_DEBUG=synthetic output/slidetool prop list ''
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux
          path: output
  macos:
    name: macOS
    runs-on: macos-latest
    steps:
      - name: Install dependencies
        run: |
          brew update
          brew install meson
      - name: Check out repo
        uses: actions/checkout@v4
      - name: Cache sources
        uses: actions/cache@v3
        with:
          key: direct-cache
          path: subprojects/packagecache
      - name: Build
        run: |
          for arch in x86_64 arm64; do
              meson setup $arch --cross-file machines/cross-macos-${arch}.ini \
                  -Dopenslide_werror=true
              meson compile -C $arch
              DESTDIR=install meson install -C $arch
          done
          mkdir output
          lipo -create {x86_64,arm64}/install/lib/libopenslide.1.dylib \
              -output output/libopenslide.1.dylib
          lipo -create {x86_64,arm64}/install/bin/slidetool \
              -output output/slidetool
          cd output
          for f in libopenslide.1.dylib slidetool; do
              dsymutil $f
              strip -u -r $f
          done
          install_name_tool -change /lib/libopenslide.1.dylib \
              '@loader_path/libopenslide.1.dylib' slidetool
      - name: Smoke test
        run: OPENSLIDE_DEBUG=synthetic output/slidetool prop list ''
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: output
